### ISSUE TITLE
Maybe a version issue. Thanks a lot for your nice work. Could you please list the versions of tensorflow and cuda?

### ISSUE THREAD

**Issue by PSGLGDnoChampion** [tymoteuszb/implicit-slam#1]
W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_ops.cc:248 : INTERNAL: Non-root tuple types are not handled.
Traceback (most recent call last):
  File "D:/cameraLocalization/imaptf/complete.py", line 859, in <module>
    mappingThread = MappingThread(sharedData)
  File "D:/cameraLocalization/imaptf/complete.py", line 693, in __init__
    self.optimize()
  File "D:/cameraLocalization/imaptf/complete.py", line 712, in optimize
    self.poses_optimizer)
  File "D:\Anaconda\envs\imap\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Anaconda\envs\imap\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: Non-root tuple types are not handled. [Op:__inference_bundle_adjust_283900]

**Comment by tym-b** [comment]
Hi,

I was running it on TF 2.6. I checked now, using a standard Colab environment with K80 GPU, and indeed there seems to be a problem you mentioned. ~~I managed to overcome it by disabling the automatic mixed precision (in `keras.mixed_precision.set_global_policy` change `mixed_float16` to `float32`). At the moment, I don't have access to an environment with mixed precision enabled GPU like Nvidia V100 or T4, so I can't check.~~

Actually, I've just got this error despite setting global policy to `float32`. I will keep investigating the issue.

**Comment by vincentcartillier** [comment]
Hi @tymoteuszb , 

Thanks for sharing your implementation. 

I am facing the same issue as mentioned above. I am running the script on Ubuntu16 with TF 2.7, and 3 TitanXp GPUs. Here is the complete log:
```
2021-12-05 22:21:08.997480: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-05 22:21:11.194260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6144 MB memory:  -> device: 0, name: TITAN Xp, pci bus id: 0000:84:00.0, compute capability: 6.1
2021-12-05 22:21:11.196314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 6144 MB memory:  -> device: 0, name: TITAN Xp, pci bus id: 0000:84:00.0, compute capability: 6.1
2021-12-05 22:21:11.201720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 11419 MB memory:  -> device: 1, name: TITAN Xp, pci bus id: 0000:87:00.0, compute capability: 6.1
2021-12-05 22:21:11.203703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 11419 MB memory:  -> device: 2, name: TITAN Xp, pci bus id: 0000:88:00.0, compute capability: 6.1
WARNING:tensorflow:Mixed precision compatibility check (mixed_float16): WARNING
Your GPUs may run slowly with dtype policy mixed_float16 because they do not have compute capability of at least 7.0. Your GPUs:
  TITAN Xp, compute capability 6.1 (x3)
See https://developer.nvidia.com/cuda-gpus for a list of GPUs and their compute capabilities.
If you will use compatible GPU(s) not attached to this host, e.g. by running a multi-worker model, you can ignore this warning. This message will only be logged once
2021-12-05 22:22:50.715338: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 6.00G (6442450944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-12-05 22:22:57.315381: I tensorflow/compiler/xla/service/service.cc:171] XLA service 0x560d2b780470 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-12-05 22:22:57.315417: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2021-12-05 22:22:57.315423: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (1): TITAN Xp, Compute Capability 6.1
2021-12-05 22:22:57.315428: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (2): TITAN Xp, Compute Capability 6.1
2021-12-05 22:22:57.555570: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-12-05 22:22:57.572077: W tensorflow/compiler/tf2xla/kernels/categorical_op.cc:128] Warning: Using tf.random.categorical with XLA compilation will ignore seeds.
2021-12-05 22:22:57.575357: W tensorflow/compiler/tf2xla/kernels/random_ops.cc:102] Warning: Using tf.random.uniform with XLA compilation will ignore seeds; consider using tf.random.stateless_uniform instead if reproducible behavior is desired. random_uniform
2021-12-05 22:22:57.575771: W tensorflow/compiler/tf2xla/kernels/random_ops.cc:57] Warning: Using tf.random.uniform with XLA compilation will ignore seeds; consider using tf.random.stateless_uniform instead if reproducible behavior is desired. random_uniform_2/RandomUniform
2021-12-05 22:22:57.585780: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:38] Ignoring Assert operator assert_none_equal/Assert/AssertGuard/Assert
2021-12-05 22:23:03.675770: I tensorflow/compiler/jit/xla_compilation_cache.cc:351] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-12-05 22:23:03.686846: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_ops.cc:248 : INTERNAL: Non-root tuple types are not handled.
Traceback (most recent call last):
  File "dense_slam_with_an_implicit_neural_representation.py", line 858, in <module>
    mappingThread = MappingThread(sharedData)
  File "dense_slam_with_an_implicit_neural_representation.py", line 693, in __init__
    self.optimize()
  File "dense_slam_with_an_implicit_neural_representation.py", line 712, in optimize
    self.poses_optimizer)
  File "/nethome/vcartillier3/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/nethome/vcartillier3/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: Non-root tuple types are not handled. [Op:__inference_bundle_adjust_275190]
```

I am looking into this as well despite not being super familiar with TF. Let us know if you find a fix!

**Comment by tym-b** [comment]
Looking at [this](https://github.com/tensorflow/tensorflow/issues/53123) issue suggests that it might be a recent problem with XLA compiler. A temporary workaround is to disable XLA compilation for bundle adjustment, by setting `jit_compile=False` above the `bundle_adjust` function. This, however, affects the performance of the mapping thread. For example, on standard Colab with K80 GPU, I needed to stretch the simulation time by the factor of 5 to get a reasonable trajectory on TUM dataset. This can be done by increasing the `time_scaling_factor` in `datasets` dictionary.

Alternatively, you could try downgrading `tensorflow-gpu` to an older version. I'd try `2.6.0` as this is the version I was originally using. I'm not sure if it's straightforward or not, as it might require downgrading CUDA driver (?)

**Comment by PSGLGDnoChampion** [comment]
Indeed caused by version. It works perfectly after I try tf2.6.0+cuda11.2+cudaDriver461.33(downloaded together with cuda11.2), even without setting  jit_compile. Now I can appreciate your fantastic work in detail XD

**Comment by vincentcartillier** [comment]
This has solved the issue for me as well.
I downgraded TF to 2.6.0 and it worked. (You'll need to downgrad Keras to 2.6.0 as well).

System env:
Ubuntu 16
CudaDriver 460.91.03
Cuda 11.2

thanks for the quick workaround!
I believe this issue can be closed now

**Comment by tym-b** [comment]
Thanks for reporting!
